language: generic

# For now, Flutter doesn't provide a canonical way to define variables at build time
# https://github.com/flutter/flutter/issues/26638

matrix:
  include:
    - name: Android Build
      language: android
      jdk: openjdk8
      android:
        components:
          - build-tools-28.0.3
          - android-28
      before_script:
        - export TZ=Asia/Seoul
        - openssl aes-256-cbc -K $encrypted_d0cc22ff5b43_key -iv $encrypted_d0cc22ff5b43_iv -in secrets.tar.enc -out secrets.tar -d
        - tar xvf secrets.tar
        - git clone https://github.com/flutter/flutter.git -b stable
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - gem install bundler && cd android && bundle install && cd ..
      script:
        - flutter doctor -v
        - bash scripts/populate_secret.sh
        - flutter build appbundle --build-number=$(expr $(date +%s) / 10)
        - cd android
        - bundle exec fastlane beta
    - name: iOS Build
      os: osx
      language: generic
      osx_image: xcode10.2
      before_script:
        - export TZ=Asia/Seoul
        - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
        - git clone https://github.com/flutter/flutter.git -b dev
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - gem install bundler
        - gem install cocoapods
        - cd ios && bundle install && cd ..
      script:
        - flutter doctor -v
        - bash scripts/populate_secret.sh
        - flutter build ios --no-codesign --build-number=$(expr $(date +%s) / 10)
        - cd ios
        - bundle exec fastlane beta
